refactor(bin) Clean up helper scripts code structure

diff --git a/bin/console b/bin/console
--- a/bin/console
+++ b/bin/console
@@ -1,8 +1,6 @@
 #!/usr/bin/env bash
 
-COMMAND=''
-
-if [[ -z "$1" ]] || [[ $1 = '-h' ]] || [[ $1 = '--help' ]]; then
+show_help_message() {
 	echo "Commands:"
 	echo "  build        Build Docker container"
 	echo "  buildnrun    Build Docker container and run it"
@@ -12,29 +10,42 @@ if [[ -z "$1" ]] || [[ $1 = '-h' ]] || [[ $1 = '--help' ]]; then
 	echo "  undocommit   Undo last commit (soft)"
 	echo "  clearcache   Delete content of cache folder (/var/cache/*.cache)"
 	echo "  freeze       Freeze pip packages into requirements.txt file"
+}
 
-	exit 0
-else
-	COMMAND=$1
-
-	if [[ $COMMAND = 'build' ]]; then
-		docker-compose build
-	elif [[ $COMMAND = 'buildnrun' ]]; then
-		docker-compose up --build --detach
-	elif [[ $COMMAND = 'stop' ]]; then
-		docker-compose down
-	elif [[ $COMMAND = 'push' ]]; then
-		#git checkout main && git merge dev && git checkout dev
-		git pull && git push && git checkout main && git pull && git merge dev && git push && git checkout dev
-	elif [[ $COMMAND = 'update' ]]; then
-		git pull && docker-compose up --build --detach
-	elif [[ $COMMAND = 'undocommit' ]]; then
-		git reset --soft HEAD~1
-	elif [[ $COMMAND = 'clearcache' ]]; then
-		rm -f var/cache/*.cache
-	elif [[ $COMMAND = 'freeze' ]]; then
-		pip freeze > requirements.txt
-	else
-		echo "Error: Command not found."
+show_error_message() {
+	echo -n $'\e[31m[Error]'
+	if [[ -n "$1" ]]; then
+		echo -n " $1"
 	fi
+	echo $'\e[39m'
+}
+
+if [[ -z "$1" ]] || [[ $1 = '-h' ]] || [[ $1 = '--help' ]]; then
+	show_help_message
+	exit 0
+fi
+
+COMMAND=$1
+
+if [[ $COMMAND = 'build' ]]; then
+	docker-compose build
+elif [[ $COMMAND = 'buildnrun' ]]; then
+	docker-compose up --build --detach
+elif [[ $COMMAND = 'stop' ]]; then
+	docker-compose down
+elif [[ $COMMAND = 'push' ]]; then
+	#git checkout main && git merge dev && git checkout dev
+	git pull && git push && git checkout main && git pull && git merge dev && git push && git checkout dev
+elif [[ $COMMAND = 'update' ]]; then
+	git pull && docker-compose up --build --detach
+elif [[ $COMMAND = 'undocommit' ]]; then
+	git reset --soft HEAD~1
+elif [[ $COMMAND = 'clearcache' ]]; then
+	rm -f var/cache/*.cache
+elif [[ $COMMAND = 'freeze' ]]; then
+	pip freeze > requirements.txt
+else
+	show_error_message "Unknown command '$COMMAND'"
+	show_help_message
+	exit 1
 fi
diff --git a/bin/newproject b/bin/newproject
--- a/bin/newproject
+++ b/bin/newproject
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
 
-BASE_DIR=~/Sites  # Goji's parent dir
+# Exit if any command fails
+set -e
+
+# Goji's default parent dir
+BASE_DIR=~/Developer
 
 if [[ -n "$1" ]]; then
 	BASE_DIR=$1
@@ -81,11 +85,9 @@ then
 	currentDir=$PWD
 	cd "$BASE_DIR/$projectName"
 	# Init project from project dir (don't show output)
-	git init >/dev/null 2>&1
-	git commit --allow-empty -m "Initial commit." >/dev/null 2>&1
-	# TODO: Change this in Git 2.28 to git init [-b|--initial-branch=] main
-	git branch -m "main"
-	git checkout -b dev >/dev/null 2>&1
+	git init --initial-branch=main > /dev/null
+	git commit --allow-empty --message "Initial commit." > /dev/null
+	git switch --create dev > /dev/null
 	# Back to original directory
 	cd $currentDir
 fi
